"""player2 and started_at null

Revision ID: c46d23c26d42
Revises: 944cd1233cb5
Create Date: 2025-11-15 17:26:44.045089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c46d23c26d42'
down_revision: Union[str, Sequence[str], None] = '944cd1233cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'player2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('games', 'player2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
